---
- hosts: web
  name: Install apache web services
  become:  yes 

  tasks: 
   - name: install apache
     yum:
        name: apache2
        state: present

   - name: start httpd
     service:
        name: httpd
        state: started 
